{
    "name": "Dynamic Approval Workflow — Core",
    "version": "19.0.1.0.0",
    "category": "Workflow",
    "summary": "Configurable multi-step approval workflows for any Odoo model",
    "author": "Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/dynamic-approval-workflow",
    "license": "AGPL-3",
    "depends": [
        "base",
        "mail",
        "queue_job",
    ],
    "external_dependencies": {
        "python": [],
    },
    "data": [
        "security/workflow_security.xml",
        "security/ir.model.access.csv",
        "data/workflow_data.xml",
        "data/mail_template_data.xml",
        "data/ir_cron_data.xml",
        "views/workflow_definition_views.xml",
        "views/workflow_instance_views.xml",
        "views/workflow_binding_views.xml",
        "views/workflow_task_views.xml",
        "views/workflow_incident_views.xml",
        "views/workflow_webhook_views.xml",
        "views/menu_views.xml",
    ],
    "demo": [
        "demo/workflow_demo.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "development_status": "Alpha",
    "maintainers": [],
}
